services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/payload
      PAYLOAD_SECRET: change-me-for-local-dev
    user: node
    # volumes:
    #   - ..:/workspaces/kulturpunkt-nordmors:cached
    working_dir: /workspaces/kulturpunkt-nordmors

  postgres:
    image: postgres:16-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payload"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
